KEYWORD_FORMAT = "format"
KEYWORD_YEAR = "year"
KEYWORD_ANALOGUE = "analogue"
KEYWORD_UPDATE = "update"

KEYWORD_UNLIMIT = "unlimit"
KEYWORD_SEMILIMIT = "semilimit"
KEYWORD_LIMIT = "limit"
KEYWORD_FORBID = "forbid"
KEYWORD_EMERGENCY = "emergency"
KEYWORD_NERF = "nerf"
KEYWORD_ERRATA = "errata"

TCG = "T"
OCG = "O"

STATUS_UNRELEASED = 0
STATUS_UNLIMITED = 1
STATUS_SEMILIMITED = 2
STATUS_LIMITED = 3
STATUS_FORBIDDEN = 4

STATUS_EMERGENCY = 'L'
STATUS_ERRATA = 'e'
STATUS_NERF = 'E'
